server:
  port : 8081
  
spring:
  application:
    name: fake-service
    
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true

# Process delay in seconds     
# processDelay: 10
